controller:
  replicaCount: 2

  ingressClassResource:
    name: nginx
    enabled: true
    default: false

  ingressClass: nginx

  service:
    type: LoadBalancer

    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "external"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"

    ports:
      http: 80
      https: 443

  metrics:
    enabled: true

defaultBackend:
  enabled: true
