{{- if .Values.ingress.enabled }}

apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}

  annotations:
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.scheme }}
    alb.ingress.kubernetes.io/target-type: {{ .Values.ingress.targetType }}
    alb.ingress.kubernetes.io/listen-ports: '{{ .Values.ingress.listenPorts }}'

    alb.ingress.kubernetes.io/healthcheck-path: /api/health
    alb.ingress.kubernetes.io/success-codes: "200"

spec:
  ingressClassName: {{ .Values.ingress.className }}

  rules:
    - http:
        paths:

          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.frontendService.name }}
                port:
                  number: {{ .Values.ingress.frontendService.port }}

          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.backendService.name }}
                port:
                  number: {{ .Values.ingress.backendService.port }}

{{- end }}