apiVersion: kyverno.io/v1

kind: ClusterPolicy

metadata:

  name: add-environment-label

spec:

  rules:

  - name: mutate-label

    match:

      any:

      - resources:

          kinds:

          - Deployment

    mutate:

      patchStrategicMerge:

        metadata:

          labels:

            environment: production
