apiVersion: v1
kind: Service

metadata:
  name: {{ include "platform-frontend.fullname" . }}
  labels:
    app: {{ include "platform-frontend.name" . }}

spec:
  type: {{ .Values.service.type }}

  selector:
    app: {{ include "platform-frontend.name" . }}

  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP